version: "3"

services:
  app:
    build: .
    command: bash -c "alembic upgrade head && python app/main.py"
    ports:
    - 8080:8080
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
#    environment:
#      - DATABASE_HOSTNAME=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5050:80"

volumes:
  postgres_db:
